[package]
name = "scratch-native"
version = "0.1.0"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
tokio = "0.1"
tokio-process="0.2"
toml="0.4"

curl= "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
fs_extra = "1"